services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_PASSWORD=rootUser
      - DB_NAME=yusuphdarbo
      - DB_USERNAME=postgres
      - secret_key=180bcdafaf6959f3ecb1fcae87efbfcdd7c970b30b8018f823d73bdb4093021b
      - algorithm=HS256
      - access_token_expire_minutes=30
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootUser
      POSTGRES_DB: yusuphdarbo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yusuphdarbo"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
