"""auto-vote

Revision ID: 15a8147065b4
Revises: 5a1a991fa188
Create Date: 2026-04-14 14:44:56.878140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "15a8147065b4"
down_revision: Union[str, Sequence[str], None] = "5a1a991fa188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["social_media_api.posts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["social_media_api.users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
        schema="social_media_api",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column("tag", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="social_media_api",
    )
    op.add_column(
        "posts",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
        schema="social_media_api",
    )
    op.drop_constraint(None, "posts", schema="social_media_api", type_="foreignkey")
    op.drop_column("posts", "user_id", schema="social_media_api")
    op.drop_table("votes", schema="social_media_api")
    # ### end Alembic commands ###
